version: '2.4'
services:
  base: &base
    build:
      args:
        RUBY_VERSION: '2.6.5'
        NODE_MAJOR: '13'
        BUNDLE_VERSION: '2.1.2'
      context: .
      dockerfile: ./Dockerfile

  backend: &backend
    <<: *base
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bunde
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    # depends_on:
      # - postgres
      # - redis

  app:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    environment:
      # - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - WEBPACKER_DEV_SERVER_HOST=webpacker

  # sidekiq:
  #   <<: *backend
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@postgres:5432

  # redis:
  #   image: redis:latest

  webpacker:
    <<: *backend
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  # postgres:
  #   image: postgres:12.1
  #   ports:
  #     - 5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  rails_cache:
  bundle:
  node_modules:
  packs:
  # postgres:
