version: '2.4'
services:
  base: &base
    build:
      args:
        RUBY_VERSION: '2.6.5'
        NODE_MAJOR: '13'
        BUNDLE_VERSION: '2.1.2'
      context: .
      dockerfile: ./Dockerfile

  backend: &backend
    <<: *base
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bunde
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    depends_on:
      - postgres

  app:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  postgres:
    image: postgres:12.1
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  rails_cache:
  bundle:
  node_modules:
  packs:
  postgres:
