default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || "postgres" %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: superadmin_development


test:
  <<: *default
  database: superadmin_test


production:
  url: <%= ENV['DATABASE_URL']  %>
