default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: superadmin_development


test:
  <<: *default
  database: superadmin_test
  host: localhost

production:
  <<: *default
  database: superadmin_production
