name: Bundler Audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bundler Audit
        run: |
          sudo gem install bundler-audit
      - name: Run Bundler Audit
        run: |
          bundle-audit check --update
