name: RuboCop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install required package
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev libncurses5-dev
        gem install bundler
        gem install rubocop rubocop-performance rubocop-rails rubocop-minitest
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
