name: RuboCop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install required package
      run: |
        sudo apt-get update
        gem install rubocop rubocop-performance rubocop-rails rubocop-minitest
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
