name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install required package
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev libncurses5-dev yarn
    - name: Build and create DB
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
    - name: Yarn setup
      run: |
        rm -rf node_modules
        rails assets:clobber
        yarn
        rails assets:precompile
        yarn install --check-files
        yarn add @rails/webpacker@next
        bundle exec rails webpacker:install
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake
