name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Install required package
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev libncurses5-dev
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Yarn setup
      run: |
        yarn add @rails/webpacker@next
        bundle exec rails webpacker:install
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:setup
        bundle exec rake
